### ISSUE TITLE
Columns missing in GBIF data

### ISSUE THREAD

**Issue by advika18** [tekritesh/bio-conservation#2]
Can we please include the scientificName in the consolidated gbif data, i need it to do an invasive species match. Species is not unique enough.

**Comment by tekritesh** [comment]
https://console.cloud.google.com/bigquery?project=molten-kit-354506&ws=!1m5!1m4!4m3!1smolten-kit-354506!2ssample_gbif_climate!3sconsolidated_UK_2022
