### ISSUE TITLE
GBIF column names

### ISSUE THREAD

**Issue by advika18** [tekritesh/bio-conservation#3]
Can we use the gbif column names as the names in a join? For example decimalLatitude instead of lat_deg? I am trying to keep my column names consistent with existing GBIF names.

**Comment by tekritesh** [comment]
https://console.cloud.google.com/bigquery?project=molten-kit-354506&ws=!1m5!1m4!4m3!1smolten-kit-354506!2ssample_gbif_climate!3sconsolidated_UK_2022
