### ISSUE TITLE
Pandas lambda apply returns a dataframe

### ISSUE THREAD

**Issue by tekritesh** [tekritesh/bio-conservation#6]
https://github.com/tekritesh/bio-conservation/blob/a2feca8229e15f731ffc35136b5b1c6c43b48900/gbif/gbif/covariates.py#L52

@advika18  Need your help here. I am not able to figure how do I return a dataframe with single row and multiple columns and append to the parent dataframe. 

The climate api at the moment returns a df like this :
![image](https://user-images.githubusercontent.com/65660549/179405286-1ca949e9-9038-4a57-afc6-6adc3233b277.png)

**Comment by advika18** [comment]
I am not sure what you mean. I need more elaboration.

**Comment by advika18** [comment]
Made some changes to the code, let me know if it works.

**Comment by tekritesh** [comment]
Thank you! Looks like it works well now.
